apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: eks_github_ecr
          image: 975722656191.dkr.ecr.eu-west-3.amazonaws.com/eks_github_ecr:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
