apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      serviceAccountName: default
      initContainers:
      - name: aws-cli
        image: amazon/aws-cli
        command: ['aws']
      containers:
        - name: sample
          image: 975722656191.dkr.ecr.eu-west-3.amazonaws.com/sample
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
