name: Node js app deploy to EKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
      id-token: write   # This is required for requesting the JWT
      
      
      contents: read    
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stableg
      id: install
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::482385139505:role/kl
        role-session-name: githubactionrolesession1
        aws-region: us-east-1
      

  

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: sample
        IMAGE_TAG: 1.1
      run: |
        echo ${{ steps.login-ecr.outputs }}
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: |
          aws sts get-caller-identity 
          aws eks --region us-east-1 update-kubeconfig --name githubactionpoc 
          eksctl get iamidentitymapping --cluster githubactionpoc
           
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
